require 'aws-sdk'

AWS.config(:access_key_id => 'AKIAJY563BTD3H4VKI4Q', :secret_access_key => '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'

development:
  AWS_ACCESS_KEY_ID: 'AKIAJY563BTD3H4VKI4Q'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'saving-all-the-animals-1351011'
test:
  AWS_ACCESS_KEY_ID: 'AKIAJY563BTD3H4VKI4Q'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'saving-all-the-animals-1351011'
production:
  AWS_ACCESS_KEY_ID: 'AKIAJY563BTD3H4VKI4Q'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'saving-all-the-animals-1351011'
